/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n5.1.6-16-g6e63e49496-20250129"
#endif /* AVUTIL_FFVERSION_H */
